language: node_js
node_js: 8.1.2
services:
- redis-server
before_script:
 - git clone https://github.com/ashwinath/operator-batch batch && cd batch && yarn && yarn test && cd ..
after_success:
- yarn coverage
